version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "finance_app"
      POSTGRES_USER: "fin_admin"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - "5434:5432"